apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::703357640656:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GFFNCFYT4ABQ
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::703357640656:role/UdacityFlaskDeployCBKubectlRole
        username: build      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-27T08:55:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1872"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2bd05de3-9e08-488c-80e1-045a77ced6b3
