
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::703357640656:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IYPHZIFM4PZP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::703357640656:role/UdacityFlaskDeployCBKubectlRole  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-27T12:46:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "25144"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ef0c563b-3cc5-4207-b961-13a26a209196