apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::703357640656:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XJ1ZBIDGE6PL
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-26T10:20:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1318"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6f7721be-43df-4f9f-bf44-3320c49941c2
